name: Build
on:
  push:
    branches: [ "main", "actions/build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_build:
    name: Build

    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build frontend
        run: |
          cd frontend
          npm install --silent
          npm run build

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build backend
        run: |
          cargo build --release --no-default-features --features=dashboard


